config/routes.rb
Rails.application.routes.draw do
  get 'booking/new'
  devise_for :users, controllers: {}
  root to: 'pages#home'
  
  # As an airport customer I would like to view lounge availability for a given date.
  get '/api/v1/lounge', to: 'api#lounge_availability_per_day', as: 'api_lounge_availability'
  # As an airport customer I would like to book a lounge for a particular day.
  post '/api/v1/lounge/book', to: 'api#lounge_book', as: 'api_lounge_book'



  get '/admin', to: 'pages#admin', as: 'admin'
  get '/admin/lounge', to: 'lounges#new', as: 'lounge_new'
  post '/admin/lounge', to: 'lounges#create', as: 'lounge_create'
  delete '/admin/lounge/:id', to: 'lounges#destroy', as: 'lounge_destroy'

  get '/admin/lounge/:id', to: 'lounges#edit', as: 'lounge_edit'
  post '/admin/lounge/:id', to: 'lounges#update', as: 'lounge_update'

  get '/admin/service', to: 'services#new', as: 'service_new'
  post '/admin/service', to: 'services#create', as: 'service_create'
  delete '/admin/service/:id', to: 'services#destroy', as: 'service_destroy'

  get '/admin/service/:id', to: 'services#edit', as: 'service_edit'
  post '/admin/service/:id', to: 'services#update', as: 'service_update'

  get '/lounge/:id', to: 'lounges#show', as: 'lounge_detail'
  post '/lounge/:id', to: 'bookings#new', as: 'lounge_book'
end

app/models/lounge.rb
class Lounge < ApplicationRecord
  has_many :bookings, dependent: :delete_all
  has_many :availabilites, dependent: :delete_all
  has_many :lounge_services
  has_many :services, :through => :lounge_services
end

app/controllers/lounges_controller.rb
require 'net/http'
require 'json'
require 'date'

class LoungesController < ApplicationController

  def new
    @lounge = Lounge.new()
    @services = Service.all
  end

  def create
    lounge_params = params.require(:lounge).permit(:name, :price, :description, :is_legacy, :capacity)
    services_params = params.require(:lounge).permit(:services => []).reject { |c| c.empty? }

    lounge = Lounge.create(lounge_params)
    services_params[:services].each do |service|
      lounge_service = LoungeService.create( { service_id: service.to_i, lounge_id: lounge[:id] } )
    end
    redirect_to admin_path
  end

  def show
    id = params[:id]
    @lounge = Lounge.find(id)
    @invitees = false
    @lounge.services.each do |item|
      p item
      if item.id == 1
        @invitees = true
      end
    end 
    @booking = Booking.new
    bookings = Booking.where(lounge_id: id)
    if @lounge[:is_legacy] == true
      @availability = Availability.where(lounge_id: id)
      bookings.each do |booking|
        @availability.map do |avai| 
          if avai[:date] == Date.parse(booking[:date_time])
            avai[:remaining] -= booking[:total_people]
          else
            avai
          end
        end
      end
    else
      @availability = []
      for item in (0...20) do
        avai_hash = {
          date: Date.today + item,
          remaining: @lounge.capacity
        }
        @availability.push(avai_hash)
      end

      bookings.each do |booking|
        @availability.map do |avai| 
          if avai[:date] == Date.parse(booking[:date_time])
            avai[:remaining] -= booking[:total_people]
          else
            avai
          end
        end
      end
    end
  end

  def edit
    id = params[:id]
    @lounge = Lounge.find(id)
  end

  def update
    lounge_params = params.require(:lounge).permit(:name, :price, :description, :capacity)
    lounge = Lounge.find(params[:id])
    lounge.update(lounge_params)
    redirect_to admin_path
  end

  def destroy
    lounge = Lounge.find(params[:id])
    lounge.delete
    redirect_to admin_path
  end

  def booking
    @lounge = params[:id]
    @user = current_user
  end
end

app/views/lounges/edit.html.erb
<h2>Edit lounge</h2>
  <%= simple_form_for @lounge, url: lounge_update_path(@lounge[:id]), method: :post do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :description  %>
  <%= f.input :is_legacy, :as => :hidden, :input_html => { :value => false } %>
  <%= f.input :capacity  %>
  <%= f.submit 'Update', class: "btn btn-success" %>
<% end %>

app/views/lounges/new.html.erb
<%= simple_form_for @lounge, url: lounge_create_path, method: :post do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :description  %>
  <%= f.input :is_legacy, :as => :hidden, :input_html => { :value => false } %>
  <%= f.input :capacity  %>
  <%=
    f.input :services, {
      as:         :check_boxes,
      collection: @services.map { |service| [service.name, service.id] },
      checked:    f.object.services
    }
  %>
  <%= f.submit 'Create', class: "btn btn-success" %>
<% end %>

app/views/lounges/show.html.erb
<h1><%= @lounge.name %></h1>
<h3><%= @lounge.description %></h3>

<div class="card-list">
  <% @availability.each do |availability| %>
    <div class="card book-card">
      <div class="card-body">
        <h4 class="card-title"><strong><%= availability[:date] %></strong></h4>
        <% if availability[:remaining] <= 0 %>
          <p class="card-text">Sold out!</p>
        <% else %>
          <p class="card-text"><%= availability[:remaining] %> spots left</p>
          <%= simple_form_for @booking, url: lounge_book_path(@lounge[:id]), method: :post do |f| %>
            <%= f.input :date_time, :as => :hidden, :input_html => { :value => availability[:date] } %>
            <%= f.input :services, {
              as:         :check_boxes,
              collection: @lounge.services.map { |service| [service.name, service.id] },
              checked:    f.object.services
            } %>
            <% if @invitees == true %>
              <%= f.input :total_people, as: :integer, label: "Invitees"   %>
            <% end %>
            <%= f.submit 'Book Now', class: "btn btn-success" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>