config/routes.rb
Rails.application.routes.draw do
  get 'booking/new'
  devise_for :users, controllers: {}
  root to: 'pages#home'
  
  # As an airport customer I would like to view lounge availability for a given date.
  get '/api/v1/lounge', to: 'api#lounge_availability_per_day', as: 'api_lounge_availability'
  # As an airport customer I would like to book a lounge for a particular day.
  post '/api/v1/lounge/book', to: 'api#lounge_book', as: 'api_lounge_book'



  get '/admin', to: 'pages#admin', as: 'admin'
  get '/admin/lounge', to: 'lounges#new', as: 'lounge_new'
  post '/admin/lounge', to: 'lounges#create', as: 'lounge_create'
  delete '/admin/lounge/:id', to: 'lounges#destroy', as: 'lounge_destroy'

  get '/admin/lounge/:id', to: 'lounges#edit', as: 'lounge_edit'
  post '/admin/lounge/:id', to: 'lounges#update', as: 'lounge_update'

  get '/admin/service', to: 'services#new', as: 'service_new'
  post '/admin/service', to: 'services#create', as: 'service_create'
  delete '/admin/service/:id', to: 'services#destroy', as: 'service_destroy'

  get '/admin/service/:id', to: 'services#edit', as: 'service_edit'
  post '/admin/service/:id', to: 'services#update', as: 'service_update'

  get '/lounge/:id', to: 'lounges#show', as: 'lounge_detail'
  post '/lounge/:id', to: 'bookings#new', as: 'lounge_book'
end

app/views/pages/admin.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span8 well">
      <ul class="nav nav-tabs">
        <li class="active"> <a href="#home" data-target="#lounges" data-toggle="tab">Lounges</a></li>
        <li><a href="#profile" data-target="#extra-services" data-toggle="tab">Extra Services</a></li>
        <li><a href="#profile" data-target="#bookings" data-toggle="tab">Bookings</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active fade in" id="lounges">
          <h2>Your lounges <span>
          <%= link_to "Create", lounge_new_path, method: :get, class: "btn btn-success" %></span></h2>
          <div class="card-list">
            <% @lounges.each do |lounge| %>
            <div class="card lounge-card">
              <div class="card-body">
                <h4 class="card-title"><strong>
                    <%= lounge[:name] %></strong></h4>
                <p class="card-text">
                  <%= lounge[:description] %>
                </p>
                <p class="card-text"><strong>$
                    <%= lounge[:price] %></strong></p>
                <%= link_to "Edit", lounge_edit_path(lounge[:id]), method: :get, class: "btn btn-warning" %>
                <%= link_to "Delete", lounge_destroy_path(lounge[:id]), method: :delete, class: "btn btn-danger" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane" id="extra-services">
          <h2>Extra services <span>
            <%= link_to "Create", service_new_path, method: :get, class: "btn btn-success" %></span></h2>
          <div class="card-list">
            <% @services.each do |service| %>
            <div class="card lounge-card">
              <div class="card-body">
                <h4 class="card-title"><strong>
                    <%= service[:name] %></strong></h4>
                <p class="card-text">$
                  <%= service[:price] %>
                </p>
                <%= link_to "Edit", service_edit_path(service[:id]), method: :get, class: "btn btn-warning" %>
                <%= link_to "Delete", service_destroy_path(service[:id]), method: :delete, class: "btn btn-danger" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        <div class="tab-pane" id="bookings">
          <h2>Bookings</h2>
          <div class="card-list">
            <% @bookings.each do |booking| %>
              <div class="card lounge-card">
                <div class="card-body">
                  <h4 class="card-title">lounge: <%= booking.lounge.name%></h4>
                  <p class="card-text">user: <%= booking.user.email%></p>
                  <p class="card-text">date: <%= booking.date_time %></p>
                  <p class="card-text">services:</p>
                  <% booking.services.each do |service| %>
                    <p class="card-text"><%= service.name %></p>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Discover our amazings lounges</h1>

<div class="card-list">
  <% @lounges.each do |lounge| %>
    <div class="card lounge-card">
      <div class="card-body">
        <h4 class="card-title"><strong><%= lounge[:name] %></strong></h4>
        <p class="card-text"><%= lounge[:description] %>
        </p>
        <p class="card-text"><strong>$ <%= lounge[:price] %></strong></p>
        <%= link_to "More info", lounge_detail_path(lounge[:id]), class:"btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>